// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByrKVJNN7RoXFPbw714tygB5pYMEVKCR8',
    appId: '1:92960888139:web:dd28bb5f2068c3a7cd04ce',
    messagingSenderId: '92960888139',
    projectId: 'project-house-rent',
    authDomain: 'project-house-rent.firebaseapp.com',
    storageBucket: 'project-house-rent.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbeyQYHvmqDE2uDrJbGkhRhj9Ufss7Ex8',
    appId: '1:92960888139:android:de32b4254a73f9fccd04ce',
    messagingSenderId: '92960888139',
    projectId: 'project-house-rent',
    storageBucket: 'project-house-rent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYOhTDSTD78AZlZafuDFuA4oDehx9Kfr8',
    appId: '1:92960888139:ios:cbe6d6d51de7310acd04ce',
    messagingSenderId: '92960888139',
    projectId: 'project-house-rent',
    storageBucket: 'project-house-rent.appspot.com',
    iosClientId: '92960888139-32h1j9s5aadnoeq40q0i6l42090q68nv.apps.googleusercontent.com',
    iosBundleId: 'com.example.houseRent',
  );
}
